services:
  backend:
    build:
      context: ./library-api
    ports:
      - "8000:8000"
    networks:
      - app-network

  frontend:
    build:
      context: ./library
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
